### ISSUE TITLE
Crash upon joining game

### ISSUE THREAD

**Issue by chadle01** [ZekerZhayard/OptiForge#10]
Mods using Forge 1.15.2-31.1.0-
OptiForge-MC1.15.2-0.1.7
MixinBootstrap-1.0.2
preview_OptiFine_1.15.2_HD_U_G1_pre13

Loads up minecraft to the menu fine, i can see optiforge in the mods loaded and optifine settings are viewable and changeable in the videos settings as normal. As soon as I join a server I get this crash and it kicks me back ot the minecraft launcher, or if i go into a single player game it locks up and upon force closing causes the same error message.

Time: 4/6/20 5:13 PM
Description: Unexpected error

java.lang.NoSuchMethodError: net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(Lnet/minecraft/client/renderer/WorldRenderer;Lcom/mojang/blaze3d/matrix/MatrixStack;FLnet/minecraft/client/renderer/Matrix4f;J)V
	at net.minecraft.client.renderer.GameRenderer.redirect$zzk000$redirect$renderWorld$1(GameRenderer.java:1485) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_228378_a_(GameRenderer.java:1001) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:688) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:mixins.optiforge.json:net.minecraft.client.renderer.MixinGameRenderer,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:925) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.0.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$462/4015102.call(Unknown Source) [forge-1.15.2-31.1.0.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}

**Comment by chadle01** [comment]
Needed to change to forge 1.15.2-31.1.30
