### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by asia-n** [ZekerZhayard/OptiForge#12]
[15:12:05] [main/INFO]: ModLauncher running: args [--username, asia_n, --version, forge-31.1.30, --gameDir, C:\Users\Amandus\Documents\Curse\Minecraft\Instances\Village in the Valley (1), --assetsDir, C:\Users\Amandus\Documents\Curse\Minecraft\Install\assets, --assetIndex, 1.15, --uuid, ccf0002d76fe4c5baa73089484813936, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768, --launchTarget, fmlclient, --fml.forgeVersion, 31.1.30, --fml.mcVersion, 1.15.2, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20200307.202953]
[15:12:05] [main/INFO]: ModLauncher 5.0.0-milestone.4+67+b1a340b starting: java version 1.8.0_51 by Oracle Corporation
[15:12:10] [main/INFO]: OptiFineTransformationService.onLoad
[15:12:10] [main/INFO]: OptiFine ZIP file: C:\Users\Amandus\Documents\Curse\Minecraft\Instances\Village in the Valley (1)\mods\preview_OptiFine_1.15.2_HD_U_G1_pre13.jar
[15:12:10] [main/INFO]: Added Lets Encrypt root certificates as additional trust
[15:12:10] [main/INFO]: OptiFineTransformationService.initialize
[15:12:10] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8 Source=file:/C:/Users/Amandus/Documents/Curse/Minecraft/Instances/Village%20in%20the%20Valley%20(1)/mods/MixinBootstrap-1.0.2.jar Service=ModLauncher Env=CLIENT
[15:12:11] [main/INFO]: [org.antlr.v4.runtime.ConsoleErrorListener:syntaxError:38]: line 10:99 token recognition error at: ';'
[15:12:12] [main/INFO]: OptiFineTransformationService.transformers
[15:12:12] [main/INFO]: Targets: 275
[15:12:13] [main/INFO]: additionalClassesLocator: [optifine., net.optifine.]
[15:12:13] [main/INFO]: Successfully loaded Mixin Connector [io.github.zekerzhayard.optiforge.asm.MixinConnector]
[15:12:13] [main/INFO]: Launching target 'fmlclient' with arguments [--version, forge-31.1.30, --gameDir, C:\Users\Amandus\Documents\Curse\Minecraft\Instances\Village in the Valley (1), --assetsDir, C:\Users\Amandus\Documents\Curse\Minecraft\Install\assets, --uuid, ccf0002d76fe4c5baa73089484813936, --username, asia_n, --assetIndex, 1.15, --accessToken, ????????, --userType, mojang, --versionType, release, --width, 1024, --height, 768]
[15:12:14] [main/INFO]: [OptiFine] *** Reflector Forge ***
[15:12:14] [main/INFO]: [OptiFine] (Reflector) Class not present: mods.betterfoliage.client.BetterFoliageClient
[15:12:15] [main/INFO]: [OptiFine] (Reflector) Constructor not present: net.minecraftforge.client.event.EntityViewRenderEvent$FogColors, params: class net.minecraft.client.renderer.FogRenderer, class net.minecraft.client.renderer.GameRenderer, class net.minecraft.client.renderer.ActiveRenderInfo, double, float, float, float
[15:12:15] [main/INFO]: [OptiFine] (Reflector) Constructor not present: net.minecraftforge.client.event.EntityViewRenderEvent$RenderFogEvent, params: class net.minecraft.client.renderer.FogRenderer, class net.minecraft.client.renderer.GameRenderer, class net.minecraft.client.renderer.ActiveRenderInfo, double, int, float
[15:12:15] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer
[15:12:15] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeBlockState.getLightValue
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.ForgeHooksClient.applyTransform
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.ForgeHooksClient.applyUVLock
[15:12:18] [main/WARN]: [OptiFine] (Reflector) More than one method found: net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast
[15:12:18] [main/WARN]: [OptiFine] (Reflector)  - public static void net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(net.minecraft.client.renderer.WorldRenderer,com.mojang.blaze3d.matrix.MatrixStack,float)
[15:12:18] [main/WARN]: [OptiFine] (Reflector)  - public static void net.minecraftforge.client.ForgeHooksClient.dispatchRenderLast(net.minecraft.client.renderer.WorldRenderer,com.mojang.blaze3d.matrix.MatrixStack,float,net.minecraft.client.renderer.Matrix4f,long)
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.ForgeHooksClient.getDamageModel
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.ForgeHooksClient.getMatrix
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.ForgeHooksClient.putQuadColor
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.ForgeHooksClient.renderFirstPersonHand
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.ForgeHooksClient.renderLitItem
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.ForgeHooksClient.transform
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Field not present: net.minecraftforge.common.ForgeConfig$Client.allowEmissiveItems
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.common.extensions.IForgeItem.getTileEntityItemStackRenderer
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.model.IModel
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Field not present: net.minecraftforge.common.ForgeMod.forgeLightPipelineEnabled
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.client.renderer.model.BlockModelDefinition.fromJson
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.client.renderer.vertex.VertexFormatElement$Usage.preDraw
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraft.client.renderer.vertex.VertexFormatElement$Usage.postDraw
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Field not found: World.tileEntitiesToBeRemoved
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.gui.GuiModList
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraft.launchwrapper.Launch
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Field not present: net.minecraftforge.client.model.pipeline.LightUtil.itemConsumer
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Method not present: net.minecraftforge.client.model.pipeline.LightUtil.renderQuadColor
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Field not present: net.minecraftforge.client.model.pipeline.LightUtil.tessellator
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.common.Loader
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Constructor not present: net.minecraftforge.client.event.RenderItemInFrameEvent, params: class net.minecraft.entity.item.ItemFrameEntity, class net.minecraft.client.renderer.entity.ItemFrameRenderer
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Constructor not present: net.minecraftforge.client.event.RenderLivingEvent$Pre, params: class net.minecraft.entity.LivingEntity, class net.minecraft.client.renderer.entity.LivingRenderer, float, double, double, double
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Constructor not present: net.minecraftforge.client.event.RenderLivingEvent$Post, params: class net.minecraft.entity.LivingEntity, class net.minecraft.client.renderer.entity.LivingRenderer, float, double, double, double
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Pre
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.client.event.RenderLivingEvent$Specials$Post
[15:12:18] [main/INFO]: [OptiFine] (Reflector) Class not present: net.minecraftforge.fml.client.SplashProgress
[15:12:18] [main/INFO]: [OptiFine] *** Reflector Vanilla ***
[15:12:19] [main/WARN]: Error loading class: net/minecraftforge/client/model/pipeline/ForgeBlockModelRenderer (java.lang.ClassNotFoundException: null)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:741)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:726)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:297)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getDeclaredFields0(Native Method)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.Class.getDeclaredFields(Class.java:1916)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:509)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:414)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraft.client.main.Main.main(SourceFile:129)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$448/1422140849.call(Unknown Source)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[15:12:19] [main/INFO]: [org.spongepowered.asm.mixin.transformer.MixinProcessor:applyMixins:362]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1052]: 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: Caused by: java.lang.reflect.InvocationTargetException
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at java.lang.reflect.Method.invoke(Method.java:497)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$448/1422140849.call(Unknown Source)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[15:12:19] [main/INFO]: [java.lang.ThreadGroup:uncaughtException:1061]: 	... 4 more
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:364)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:206)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:109)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:135)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:115)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:239)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:126)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:96)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.Class.getDeclaredFields0(Native Method)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.Class.privateGetDeclaredFields(Class.java:2583)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at java.lang.Class.getDeclaredFields(Class.java:1916)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.optifine.reflect.FieldLocatorTypes.<init>(FieldLocatorTypes.java:25)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.optifine.reflect.Reflector.<clinit>(Reflector.java:509)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_71504_g(CrashReport.java:101)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.<init>(CrashReport.java:54)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.crash.CrashReport.func_230188_h_(CrashReport.java:414)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	at net.minecraft.client.main.Main.main(SourceFile:129)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:643]: 	... 11 more
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: Caused by: org.spongepowered.asm.mixin.throwables.ClassMetadataNotFoundException: net.minecraftforge.client.model.pipeline.ForgeBlockModelRenderer
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transformMethod(MixinPreProcessorStandard.java:741)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.transform(MixinPreProcessorStandard.java:726)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attach(MixinPreProcessorStandard.java:297)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.createContextFor(MixinPreProcessorStandard.java:267)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinInfo.createContextFor(MixinInfo.java:1271)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:287)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:570)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[15:12:19] [main/INFO]: [java.lang.Throwable:printStackTrace:667]: 	... 29 more

**Comment by ZekerZhayard** [comment]
OptiForge 0.1.8 requires forge-1.15.2-31.1.39
