### ISSUE TITLE
Crash with Forge: 31.1.45

### ISSUE THREAD

**Issue by DMCK96** [ZekerZhayard/OptiForge#17]
**How to reproduce:** Use the following mod versions and attempt to launch the game.

**Modpack:** FTB Omnia 1.2.0
**Optifine:** preview_OptiFine_1.15.2_HD_U_G1_pre12
**Optiforge:** OptiForge-MC1.15.2-0.1.10
**Mixin:** 1.0.2
**Forge:** 31.1.45

> `java.lang.ExceptionInInitializerError: null
	at net.minecraft.client.gui.fonts.FontResourceManager.func_212318_b(SourceFile:152) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.FontResourceManager$$Lambda$5249/1069703607.apply(Unknown Source) ~[?:?] {}
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118) ~[?:1.8.0_51] {}
	at net.minecraft.client.gui.fonts.FontResourceManager.func_211504_a(SourceFile:151) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:409) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs.mixins.json:MinecraftMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.45.jar:31.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$463/131709548.call(Unknown Source) [forge-1.15.2-31.1.45.jar:31.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {}`

**Full Stacktrace:** https://gist.github.com/DMCK96/6ad96f8376ebc54c1316671932ee7b69

**Comment by ZekerZhayard** [comment]
this is not an optiforge issue
https://pastebin.com/VSs3Gby7

**Comment by DMCK96** [comment]
> this is not an optiforge issue
> https://pastebin.com/VSs3Gby7

Can you explain further, please? Is it an optifine issue? Is it another mod conflicting with optfine or optiforge?

**Comment by ZekerZhayard** [comment]
I'm not very clear about what cause this crash, but it doesn't look like caused by optiforge
