### ISSUE TITLE
Crashing on opening

### ISSUE THREAD

**Issue by CaliHugz** [ZekerZhayard/OptiForge#48]
---- Minecraft Crash Report ----
// You're mean.

Time: 10/5/20 9:09 PM
Description: Initializing game

java.lang.NullPointerException: Initializing game
	at org.objectweb.asm.Frame.merge(Frame.java:1171) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767) ~[asm-tree-7.2.jar:7.2] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647) ~[asm-tree-7.2.jar:7.2] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:408) ~[asm-tree-7.2.jar:7.2] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:132) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:256) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135) ~[modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97) ~[modlauncher-7.0.1.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:452) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.5.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/810262298.call(Unknown Source) [forge-1.16.3-34.1.5.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at org.objectweb.asm.Frame.merge(Frame.java:1171) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.MethodWriter.computeAllFrames(MethodWriter.java:1610) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.MethodWriter.visitMaxs(MethodWriter.java:1546) ~[asm-7.2.jar:7.2] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:767) ~[asm-tree-7.2.jar:7.2] {}
	at org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:647) ~[asm-tree-7.2.jar:7.2] {}
	at org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:408) ~[asm-tree-7.2.jar:7.2] {}
	at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:132) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:256) ~[modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:135) ~[modlauncher-7.0.1.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:97) ~[modlauncher-7.0.1.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_51] {}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:452) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.5.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$426/810262298.call(Unknown Source) [forge-1.16.3-34.1.5.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

-- System Details --
Details:
	Minecraft Version: 1.16.3
	Minecraft Version ID: 1.16.3
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 507016448 bytes (483 MB) / 1644167168 bytes (1568 MB) up to 2147483648 bytes (2048 MB)
	CPUs: 12
	JVM Flags: 9 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	ModLauncher: 7.0.1+78+master.e9771d8
	ModLauncher launch target: fmlclient
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.1.jar mixin PLUGINSERVICE 
		/eventbus-3.0.3-service.jar eventbus PLUGINSERVICE 
		/forge-1.16.3-34.1.5.jar object_holder_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.5.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-2.2.0-shadowed.jar accesstransformer PLUGINSERVICE 
		/forge-1.16.3-34.1.5.jar capability_inject_definalize PLUGINSERVICE 
		/forge-1.16.3-34.1.5.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.1.jar mixin TRANSFORMATIONSERVICE 
		/preview_OptiFine_1.16.3_HD_U_G4_pre1%20(1).jar OptiFine TRANSFORMATIONSERVICE 
		/OptiForge-Mod-1.16.3.jar optiforge TRANSFORMATIONSERVICE 
		/forge-1.16.3-34.1.5.jar fml TRANSFORMATIONSERVICE 
		/OptiForge-Mod-1.16.3.jar FakeOptiFine TRANSFORMATIONSERVICE 
		/OptiForge-Mod-1.16.3.jar optiforgewrapper TRANSFORMATIONSERVICE 
	FML: 34.1
	Forge: net.minecraftforge:34.1.5
	FML Language Providers: 
		javafml@34.1
		minecraft@1
	Mod List: 
		forge-1.16.3-34.1.5-client.jar Minecraft {minecraft@1.16.3 COMMON_SETUP}
		OptiForge-Mod-1.16.3.jar OptiForge {optiforge@0.3.2 COMMON_SETUP}
		forge-1.16.3-34.1.5-universal.jar Forge {forge@34.1.5 COMMON_SETUP}
	Launched Version: 1.16.3-forge-34.1.5
	Backend library: LWJGL version 3.2.2 build 10
	Backend API: GeForce GTX 1660/PCIe/SSE2 GL version 4.6.0 NVIDIA 446.14, NVIDIA Corporation
	GL Caps: Using framebuffer using OpenGL 3.0
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'forge'
	Type: Client (map_client.txt)
	CPU: 12x Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz

**Comment by CaliHugz** [comment]
Nvm I fixed by moving from preview to normal optifine.

**Comment by lulabyte** [comment]
What do you mean moving "from preview to normal optifine"? I am also having this issue crashing on loading in 1.16.1

**Comment by ZekerZhayard** [comment]
It seems you were using an old optiforge version.
