### ISSUE TITLE
Any clues about OptiFine 1.17.1 HD U G9 Release?

### ISSUE THREAD

**Issue by Marcelo-Petrucelli** [ZekerZhayard/OptiForge#97]
I'm getting this error when trying to load "OptiFine 1.17.1 HD U G9", but the release version.

I simply can't download the version pre33 anymore, which is the one that shows as supported by Optiforge.
Oh, I'm using Forge-37.0.90

> Exception in thread "main" java.lang.module.ResolutionException: Modules OptiFine._1._17._1.HD.U.G9 and eventbus export package net.minecraftforge.eventbus.api to module io.github.zekerzhayard.optiforge
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:908)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:822)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:743)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:379)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:82)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.discoverServices(TransformationServicesHandler.java:129)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)

**Comment by ZekerZhayard** [comment]
why not use the preview version directly without optiforge?
and optifine G9 should not be installed in mods folder

**Comment by Marcelo-Petrucelli** [comment]
Thanks for the answer @ZekerZhayard. Yeah, just noticed that there is the preview version to be used without Optiforge. And yeah, I did not install neither of them, just threw them into the mods folder.

Thanks anyway
